name: "Python Semantic Release"
description: "An action to run release a python package with semantic release"
runs:
  using: "composite"
  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.BOT_ID }}
        private-key: ${{ secrets.BOT_SK }}

    - name: pre-commit and pytest
      run: |
        set -o pipefail
        poetry run pre-commit run --all-files && git diff --exit-code
        poetry run pytest

    - name: Set Git user as GitHub actions
      run: git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

    - name: Update release
      run: poetry run semantic-release --strict version
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Create Wheel
      run: poetry build --format wheel

    - uses: actions/upload-artifact@v4 # upload artifacts so they are retained on the job
      with:
        path: dist

    - name: Publish to GitHub
      run: poetry run semantic-release publish
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
