name: "Setup Algokit Python Environment"
description: "An action to setup the python environment with algokit and uv"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: uv sync --group dev

    - name: Install algokit
      shell: bash
      run: pipx install algokit

    - name: Run localnet
      shell: bash
      run: algokit localnet start
