name: "Setup Algokit Python Environment"
description: "An action to setup the python environmen with algokit and poetry"
runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Install algokit
      run: pipx install algokit

    - name: Run localnet
      run: algokit localnet start
