name: Continuous Delivery of Python package

on:
  push:
    branches:
      - main
      - release/*

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  release:
    name: Release Library
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
      packages: read
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}
      - uses: actions/checkout@v4
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install algokit
        run: pipx install algokit

      - name: pre-commit and pytest
        run: |
          set -o pipefail
          source $(poetry env info --path)/bin/activate
          pre-commit run --all-files && git diff --exit-code
          algokit localnet start
          pytest

      - name: Set Git user as GitHub actions
        run: git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Update release
        run: poetry run semantic-release --strict version
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Create Wheel
        run: poetry build --format wheel

      - uses: actions/upload-artifact@v4 # upload artifacts so they are retained on the job
        with:
          path: dist

      - name: Publish to GitHub
        run: poetry run semantic-release publish
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-docs:
    name: Publish Docs
    # Don't publish canary docs
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/gh-pages.yaml
    permissions:
      contents: read
      pages: write
      id-token: write
