name: "Starlight: Render + publish docs"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build documentation
        uses: ./.github/actions/publish-docs

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
